# Introduction
The Application *Key Entry* (`keyEntry-App`) has been developed under the SASSCAL initiative (http://www.sasscal.org) through the Climate Task *Historical and ongoing climate data management* to facilitate the key entry of climate data in the meteorological services of Angola, Botswana and Zambia.

The App gives the user a web-based interface to enter the data in the same way as they are in the on-paper form. The user can also custom the structure of the forms and create their own templates. It includes an *in-situ* quality control based on absolute limits, so that the user will be aware if a key entered value is outside the limits.

The tool has been developed under Shiny, an open source R package that provides a powerful web framework for building web applications using R (<https://shiny.rstudio.com/>). Shiny helps turn data analyses into interactive web applications without requiring HTML, CSS, or JavaScript knowledge ([RStudio, 2017](#references))

This manual will give an overview of the Application, explaining how to install it, how to run it and how to use it. 


 